### PR TITLE
Add Github Action to update Hugo site

### PR DESCRIPTION
**Pull request by rolfkleef**
To be added to master branch
Then, cms branch can contain Hugo sources, and on each push to cms, the site will be updated

### CODE REVIEW

**Comment by rolfkleef** [comment]
if you like I can add you to a sandbox I've used to experiment in https://github.com/utgardr/utgardr.github.io

**Comment by cirulls** [comment]
@rolfkleef: I tested the GitHub Action on a [fork of your sandbox repository](https://github.com/cirulls/utgardr.github.io/runs/703523153?check_suite_focus=true) and it worked perfectly. My only suggestion would be to rename the branch, I would prefer something like `hugo` instead of `cms` as branch name since Hugo is technically not a CMS. Sorry to nitpick... 

Notes to myself when pushing the hugo files: the submodule `themes/hyde-hyde` needs to be added in `.gitmodules` as follows:
```
[submodule "themes/hyde-hyde"] 
    path = themes/hyde-hyde 
    url = https://github.com/htr3n/hyde-hyde
```

**Comment by rolfkleef** [comment]
I've changed it to `hugo`, was also wondering what to choose. I figured git is the "cms" :-)

**Comment by cirulls** [comment]
@rolfkleef: thanks for the change. I'll merge this PR during the weekend when I'll have a bit more time to observe it and commit the hugo files. I'll keep you posted.

**Comment by cirulls** [comment]
I merged the PR, pushed branch `hugo` and the GitHub Action worked perfectly and regenerated the website. Thanks a lot for this contribution, it's really useful!

In the next days I will clean up the hugo branch (I think there are several unnecessary files) and write some instructions how to add content to the website.

**Pull request merged**
